source 'https://rubygems.org'

gem 'sinatra', git: 'https://github.com/sinatra/sinatra.git'
gem 'yard'
gem 'sqlite3'
gem 'json'
gem 'sinatra-activerecord'
gem 'bcrypt'
gem 'rack'
gem 'rack-test'
gem 'rake'
gem 'minitest'
gem 'pg'
